### PR TITLE
feat(tooling): add semantic-release, cz-changelog and commitizen

### PR DESCRIPTION
**Pull request by leandrogrillo**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c919fed04dd75778c6576da4f9d4fae6a3055f51
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/leroy-merlin-br/shared-ui-react

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 88fc2932fe8370262a3c4da511ba22db38770d05
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: c75b2d9f5eae095cc7795c6a33e2f16970854fea
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/leroy-merlin-br/shared-ui-react

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 88fc2932fe8370262a3c4da511ba22db38770d05
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: c75b2d9f5eae095cc7795c6a33e2f16970854fea
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: ed9722084e5f6f2f3443472d8ce6a6ccbcc7e126
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 35b0fa8848f1f1358b6b3fa9104099de7fad307c
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/leroy-merlin-br/shared-ui-react

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 88fc2932fe8370262a3c4da511ba22db38770d05
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: c75b2d9f5eae095cc7795c6a33e2f16970854fea
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: ed9722084e5f6f2f3443472d8ce6a6ccbcc7e126
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 35b0fa8848f1f1358b6b3fa9104099de7fad307c
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: a8866a830762d2d5a6b1ab7a121e6c2e39cbd3dd
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/leroy-merlin-br/shared-ui-react

---
This message was auto-generated by https://gitcop.com

**Comment by andreolvr** [comment]
I deleted the GitCop comments on this PR since we are CommitLint now. Don't forget to rebase your branch with master since i just merged the CommitLint PR :)

**Pull request merged**
